### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by joshuanianji** [michidk/devcontainers-features#4]
Typst has started to include `aarch` binaries in their releases starting from [`v0.3.0`](https://github.com/typst/typst/releases/tag/v0.3.0). Currently, the install script fails when the architecture is not `amd64`, would you be interested in adding support for arm?

**Comment by michidk** [comment]
This makes total sense. Feel free to open a pull request!

**Comment by joshuanianji** [comment]
Great, thanks!
